### ISSUE TITLE
Package 'acl' is not installed. This is required for Ansible

### ISSUE THREAD

**Issue by amirulalif** [thesplunker/Splunkenizer#36]
**Describe the bug**
```
Got error "Package 'acl' is not installed. This is required for Ansible." when running command  
ansible-playbook ansible/deploy_site.yml
```

**To Reproduce**
 - provide splunk_config.yml
 ```
 ---
# splunk_config.yml
plugin: splunk-platform-automator

virtualbox:
#  box: "centos/7" # Default
  box: "ubuntu/jammy64"

# Splunk default settings
splunk_defaults:
   splunk_env_name: splk
   splunk_version: '9.1.1'
   splunk_admin_password: 'password'
   splunk_license_file: Splunk_Enterprise.lic
  # splunk_indexes:
  #   test1:
  #   test2_metrics:
  #     datatype: metric

# Splunk hosts with its settings
splunk_hosts:
  # Indexer and Search Head on single node
  - name: shidx
    roles:
      - indexer
      - search_head

   # Universal Forwarder
#  - name: uf
#    roles:
#      - universal_forwarder
 ```
 - provide exact commands you executed
 ```
$ ansible-playbook ansible/deploy_site.yml
 ```

**Screenshots**
![splunk-acl-issue](https://github.com/splunk/splunk-platform-automator/assets/20899877/89ea9d49-2313-4adf-8607-dcd92676000d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Ansible Version [2.12.0]

**Already try**
```
# apt install acl
But still error
```
