### ISSUE TITLE
Special characters in Splunk password

### ISSUE THREAD

**Issue by bojanjanisch** [thesplunker/Splunkenizer#6]
**Describe the bug**
When using special characters in the Splunk password the Splunk setup crashes.

**To Reproduce**
```
general:
  start_ip: 172.16.1.100

virtualbox:
    box: "centos/7" # Default

splunk_defaults:
    splunk_env_name: splk
    splunk_version: '6.5.7'
    splunk_admin_password: '$plunkLab'


splunk_hosts:
  - name: shidx
    roles:
      - indexer
      - search_head
```
**Expected behavior**
The password set should be $plunkLab.

**Desktop (please complete the following information):**
 - OS: CentOS
 - Ansible Version 2.7

**Additional context**
I fixed this issue by putting the password in the ansible scripts into single quotes.
